// Interfaces for all message types we send to the FAF server.

/**
 * Base interface for all messages we send to the server.
 */
export interface ServerMessage {
    // The type of the message.
    command:string;
}

export interface AskSessionMessage extends ServerMessage {
    command:"ask_session";

    // A string identifying the version of the client.
    version:string;

    // A string identifying the client.
    user_agent:string;
}

export interface LoginMessage extends ServerMessage {
    command:"hello";

    // The name of the user logging in.
    login:string;

    // sha256 of the user's password.
    password:string;

    // The uid generated by the uid binary.
    unique_uid:string;

    // The session ID the server sent you in response to the AskSessionMessage.
    session:string;
}

