// Interfaces for all message types we send to the FAF server.

/**
 * Base interface for all messages we send to the server.
 */
export interface OutboundMessage {
    // The type of the message.
    command:string;
}

export interface AskSession extends OutboundMessage {
    command:"ask_session";

    // A string identifying the version of the client.
    version:string;

    // A string identifying the client.
    user_agent:string;
}

export interface Login extends OutboundMessage {
    command:"hello";

    // The name of the user logging in.
    login:string;

    // sha256 of the user's password.
    password:string;

    // The uid generated by the uid binary.
    unique_id:string;
}


/**
 * Base interface for all messages we receive from the server.
 */
export interface InboundMessage {
    // The type of the message.
    command:string;
}

/**
 * Message providing your session ID. Received in response to the client sending version information
 * and passing the check (otherwise an Update message is sent, notifying the client that it is out
 * of date).
 */
export interface Session extends InboundMessage {
    command: "session";

    // This connection's unique session ID number.
    session: number;
}

/**
 * Message indicating that the client is too outdated for the server's liking.
 */
export interface Update extends InboundMessage {
    command: "update";

    // A URL to download the newest version.
    update: string;

    // The version number of the client available at the given download link.
    new_version: string;
}

/**
 * Sent when authentication succeeds. The server sends you your own player info object.
 */
export interface Welcome extends InboundMessage {
    command: "welcome";

    // A Player object representing yourself.
    // me: Player;
}

/**
 * Provides information about one or more players.
 */
export interface PlayerInfo extends InboundMessage {
    
}

/**
 *
 */
export interface Stats extends InboundMessage {

}
